camel:
  springboot:
    name: account-service
    main-run-controller: true
  zipkin:
    host-name: localhost
    port: 9410
    server-service-mappings.direct*: consul-acc-reg
    client-service-mappings.direct*: consul-acc-reg
    server-service-mappings.route*: account-service
    client-service-mappings.route*: account-service
        
logging:
  level:
    org.apache.camel: DEBUG